spring.application.name=course-registration-system

spring.devtools.restart.enabled=true  
spring.devtools.livereload.enabled=true  

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:mydatabase.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
